setwd("C:/Users/mswatson/Documents/COURSERA/")
if(!file.exists("./fproject")) {dir.create("./fproject")}
fileUrl <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip?accessType=DOWNLOAD"
download.file(fileUrl,destfile="./fproject/getdata_projectfiles_UCI HAR Dataset.zip", mode = 'wb')
unzip("./fproject/getdata_projectfiles_UCI HAR Dataset.zip", exdir="./fprojunzip")

Xtest <- read.table("./fprojunzip/UCI HAR Dataset/test/X_test.txt")
ytest <- read.table("./fprojunzip/UCI HAR Dataset/test/y_test.txt")
Xtest2 <- cbind(Xtest, ytest)
subtest <- read.table("./fprojunzip/UCI HAR Dataset/test/subject_test.txt")
Xtest3 <- cbind(Xtest2, subtest)

Xtrain <- read.table("./fprojunzip/UCI HAR Dataset/train/X_train.txt")
ytrain <- read.table("./fprojunzip/UCI HAR Dataset/train/y_train.txt")
subtrain <- read.table("./fprojunzip/UCI HAR Dataset/train/subject_train.txt")
Xtrain2 <-cbind(Xtrain, ytrain)
Xtrain3 <-cbind(Xtrain2, subtrain)


mergeData <- rbind(Xtest3, Xtrain3)


colnames(mergeData) <- c("tBodyAccMeanx",
                         "tBodyAccmeanY",
                         "tBodyAccMeanZ",
                         "tBodyAccStdX",
                         "tBodyAccStdY",
                         "tBodyAccStdZ",
                         "tBodyAccmadX",
                         "tBodyAccmadY",
                         "tBodyAccmadZ",
                         "tBodyAccmaxX",
                         "tBodyAccmaxY",
                         "tBodyAccmaxZ",
                         "tBodyAccminX",
                         "tBodyAccminY",
                         "tBodyAccminZ",
                         "tBodyAccsma",
                         "tBodyAccenergyX",
                         "tBodyAccenergyY",
                         "tBodyAccenergyZ",
                         "tBodyAcciqrX",
                         "tBodyAcciqrY",
                         "tBodyAcciqrZ",
                         "tBodyAccentropyX",
                         "tBodyAccentropyY",
                         "tBodyAccentropyZ",
                         "tBodyAccarCoeffX1",
                         "tBodyAccarCoeffX2",
                         "tBodyAccarCoeffX3",
                         "tBodyAccarCoeffX4",
                         "tBodyAccarCoeffY1",
                         "tBodyAccarCoeffY2",
                         "tBodyAccarCoeffY3",
                         "tBodyAccarCoeffY4",
                         "tBodyAccarCoeffZ1",
                         "tBodyAccarCoeffZ2",
                         "tBodyAccarCoeffZ3",
                         "tBodyAccarCoeffZ4",
                         "tBodyAcccorrelationXY",
                         "tBodyAcccorrelationXZ",
                         "tBodyAcccorrelationYZ",
                         "tGravityAccMeanX",
                         "tGravityAccMeanY",
                         "tGravityAccMeanZ",
                         "tGravityAccStdX",
                         "tGravityAccStdY",
                         "tGravityAccStdZ",
                         "tGravityAccmadX",
                         "tGravityAccmadY",
                         "tGravityAccmadZ",
                         "tGravityAccmaxX",
                         "tGravityAccmaxY",
                         "tGravityAccmaxZ",
                         "tGravityAccminX",
                         "tGravityAccminY",
                         "tGravityAccminZ",
                         "tGravityAccsma",
                         "tGravityAccenergyX",
                         "tGravityAccenergyY",
                         "tGravityAccenergyZ",
                         "tGravityAcciqrX",
                         "tGravityAcciqrY",
                         "tGravityAcciqrZ",
                         "tGravityAccentropyX",
                         "tGravityAccentropyY",
                         "tGravityAccentropyZ",
                         "tGravityAccarCoeffX1",
                         "tGravityAccarCoeffX2",
                         "tGravityAccarCoeffX3",
                         "tGravityAccarCoeffX4",
                         "tGravityAccarCoeffY1",
                         "tGravityAccarCoeffY2",
                         "tGravityAccarCoeffY3",
                         "tGravityAccarCoeffY4",
                         "tGravityAccarCoeffZ1",
                         "tGravityAccarCoeffZ2",
                         "tGravityAccarCoeffZ3",
                         "tGravityAccarCoeffZ4",
                         "tGravityAcccorrelationXY",
                         "tGravityAcccorrelationXZ",
                         "tGravityAcccorrelationYZ",
                         "tBodyAccJerkMeanX",
                         "tBodyAccJerkMeanY",
                         "tBodyAccJerkMeanZ",
                         "tBodyAccJerkStdX",
                         "tBodyAccJerkStdY",
                         "tBodyAccJerkStdZ",
                         "tBodyAccJerkMadX",
                         "tBodyAccJerkMadY",
                         "tBodyAccJerkMadZ",
                         "tBodyAccJerkMaxX",
                         "tBodyAccJerkMaxY",
                         "tBodyAccJerkMaxZ",
                         "tBodyAccJerkMinX",
                         "tBodyAccJerkMinY",
                         "tBodyAccJerkMinZ",
                         "tBodyAccJerksma",
                         "tBodyAccJerkenergyX",
                         "tBodyAccJerkenergyY",
                         "tBodyAccJerkenergyZ",
                         "tBodyAccJerkiqrX",
                         "tBodyAccJerkiqrY",
                         "tBodyAccJerkiqrZ",
                         "tBodyAccJerkentropyX",
                         "tBodyAccJerkentropyY",
                         "tBodyAccJerkentropyZ",
                         "tBodyAccJerkarCoeffX1",
                         "tBodyAccJerkarCoeffX2",
                         "tBodyAccJerkarCoeffX3",
                         "tBodyAccJerkarCoeffX4",
                         "tBodyAccJerkarCoeffY1",
                         "tBodyAccJerkarCoeffY2",
                         "tBodyAccJerkarCoeffY3",
                         "tBodyAccJerkarCoeffY4",
                         "tBodyAccJerkarCoeffZ1",
                         "tBodyAccJerkarCoeffZ2",
                         "tBodyAccJerkarCoeffZ3",
                         "tBodyAccJerkarCoeffZ4",
                         "tBodyAccJerkcorrelationXY",
                         "tBodyAccJerkcorrelationXZ",
                         "tBodyAccJerkcorrelationYZ",
                         "tBodyGyroMeanX",
                         "tBodyGyroMeanY",
                         "tBodyGyroMeanZ",
                         "tBodyGyroStdX",
                         "tBodyGyroStdY",
                         "tBodyGyroStdZ",
                         "tBodyGyromadX",
                         "tBodyGyromadY",
                         "tBodyGyromadZ",
                         "tBodyGyromaxX",
                         "tBodyGyromaxY",
                         "tBodyGyromaxZ",
                         "tBodyGyrominX",
                         "tBodyGyrominY",
                         "tBodyGyrominZ",
                         "tBodyGyrosma",
                         "tBodyGyroenergyX",
                         "tBodyGyroenergyY",
                         "tBodyGyroenergyZ",
                         "tBodyGyroiqrX",
                         "tBodyGyroiqrY",
                         "tBodyGyroiqrZ",
                         "tBodyGyroentropyX",
                         "tBodyGyroentropyY",
                         "tBodyGyroentropyZ",
                         "tBodyGyroarCoeffX1",
                         "tBodyGyroarCoeffX2",
                         "tBodyGyroarCoeffX3",
                         "tBodyGyroarCoeffX4",
                         "tBodyGyroarCoeffY1",
                         "tBodyGyroarCoeffY2",
                         "tBodyGyroarCoeffY3",
                         "tBodyGyroarCoeffY4",
                         "tBodyGyroarCoeffZ1",
                         "tBodyGyroarCoeffZ2",
                         "tBodyGyroarCoeffZ3",
                         "tBodyGyroarCoeffZ4",
                         "tBodyGyrocorrelationXY",
                         "tBodyGyrocorrelationXZ",
                         "tBodyGyrocorrelationYZ",
                         "tBodyGyroJerkMeanX",
                         "tBodyGyroJerkMeanY",
                         "tBodyGyroJerkMeanZ",
                         "tBodyGyroJerkStdX",
                         "tBodyGyroJerkStdY",
                         "tBodyGyroJerkStdZ",
                         "tBodyGyroJerkmadX",
                         "tBodyGyroJerkmadY",
                         "tBodyGyroJerkmadZ",
                         "tBodyGyroJerkmaxX",
                         "tBodyGyroJerkmaxY",
                         "tBodyGyroJerkmaxZ",
                         "tBodyGyroJerkminX",
                         "tBodyGyroJerkminY",
                         "tBodyGyroJerkminZ",
                         "tBodyGyroJerksma",
                         "tBodyGyroJerkenergyX",
                         "tBodyGyroJerkenergyY",
                         "tBodyGyroJerkenergyZ",
                         "tBodyGyroJerkiqrX",
                         "tBodyGyroJerkiqrY",
                         "tBodyGyroJerkiqrZ",
                         "tBodyGyroJerkentropyX",
                         "tBodyGyroJerkentropyY",
                         "tBodyGyroJerkentropyZ",
                         "tBodyGyroJerkarCoeffX1",
                         "tBodyGyroJerkarCoeffX2",
                         "tBodyGyroJerkarCoeffX3",
                         "tBodyGyroJerkarCoeffX4",
                         "tBodyGyroJerkarCoeffY1",
                         "tBodyGyroJerkarCoeffY2",
                         "tBodyGyroJerkarCoeffY3",
                         "tBodyGyroJerkarCoeffY4",
                         "tBodyGyroJerkarCoeffZ1",
                         "tBodyGyroJerkarCoeffZ2",
                         "tBodyGyroJerkarCoeffZ3",
                         "tBodyGyroJerkarCoeffZ4",
                         "tBodyGyroJerkcorrelationXY",
                         "tBodyGyroJerkcorrelationXZ",
                         "tBodyGyroJerkcorrelationYZ",
                         "tBodyAccMagMean",
                         "tBodyAccMagStd",
                         "tBodyAccMagmad",
                         "tBodyAccMagmax",
                         "tBodyAccMagmin",
                         "tBodyAccMagsma",
                         "tBodyAccMagenergy",
                         "tBodyAccMagiqr",
                         "tBodyAccMagentropy",
                         "tBodyAccMagarCoeff1",
                         "tBodyAccMagarCoeff2",
                         "tBodyAccMagarCoeff3",
                         "tBodyAccMag-arCoeff4",
                         "tGravityAccMagMean",
                         "tGravityAccMagStd",
                         "tGravityAccMagmad",
                         "tGravityAccMagmax",
                         "tGravityAccMagmin",
                         "tGravityAccMagsma",
                         "tGravityAccMagenergy",
                         "tGravityAccMagiqr",
                         "tGravityAccMagentropy",
                         "tGravityAccMagarCoeff1",
                         "tGravityAccMagarCoeff2",
                         "tGravityAccMagarCoeff3",
                         "tGravityAccMagarCoeff4",
                         "tBodyAccJerkMagMean",
                         "tBodyAccJerkMagStd",
                         "tBodyAccJerkMagmad",
                         "tBodyAccJerkMagmax",
                         "tBodyAccJerkMagmin",
                         "tBodyAccJerkMagsma",
                         "tBodyAccJerkMagenergy",
                         "tBodyAccJerkMagiqr",
                         "tBodyAccJerkMagentropy",
                         "tBodyAccJerkMagarCoeff1",
                         "tBodyAccJerkMagarCoeff2",
                         "tBodyAccJerkMagarCoeff3",
                         "tBodyAccJerkMagarCoeff4",
                         "tBodyGyroMagMean",
                         "tBodyGyroMagStd",
                         "tBodyGyroMagmad",
                         "tBodyGyroMagmax",
                         "tBodyGyroMagmin",
                         "tBodyGyroMagsma",
                         "tBodyGyroMagenergy",
                         "tBodyGyroMagiqr",
                         "tBodyGyroMagentropy",
                         "tBodyGyroMagarCoeff1",
                         "tBodyGyroMagarCoeff2",
                         "tBodyGyroMagarCoeff3",
                         "tBodyGyroMagarCoeff4",
                         "tBodyGyroJerkMagMean",
                         "tBodyGyroJerkMagStd",
                         "tBodyGyroJerkMagmad",
                         "tBodyGyroJerkMagmax",
                         "tBodyGyroJerkMagmin",
                         "tBodyGyroJerkMagsma",
                         "tBodyGyroJerkMagenergy",
                         "tBodyGyroJerkMagiqr",
                         "tBodyGyroJerkMagentropy",
                         "tBodyGyroJerkMagarCoeff1",
                         "tBodyGyroJerkMagarCoeff2",
                         "tBodyGyroJerkMagarCoeff3",
                         "tBodyGyroJerkMagarCoeff4",
                         "fBodyAccMeanX",
                         "fBodyAccMeanY",
                         "fBodyAccMeanZ",
                         "fBodyAccStdX",
                         "fBodyAccStdY",
                         "fBodyAccStdZ",
                         "fBodyAccmadX",
                         "fBodyAccmadY",
                         "fBodyAccmadZ",
                         "fBodyAccmaxX",
                         "fBodyAccmaxY",
                         "fBodyAccmaxZ",
                         "fBodyAccminX",
                         "fBodyAccminY",
                         "fBodyAccminZ",
                         "fBodyAccsma",
                         "fBodyAccenergyX",
                         "fBodyAccenergyY",
                         "fBodyAccenergyZ",
                         "fBodyAcciqrX",
                         "fBodyAcciqrY",
                         "fBodyAcciqrZ",
                         "fBodyAccentropyX",
                         "fBodyAccentropyY",
                         "fBodyAccentropyZ",
                         "fBodyAccmaxInds-X",
                         "fBodyAccmaxInds-Y",
                         "fBodyAccmaxInds-Z",
                         "fBodyAccMeanFreqX",
                         "fBodyAccMeanFreqY",
                         "fBodyAccMeanFreqZ",
                         "fBodyAccskewnessX",
                         "fBodyAcckurtosisX",
                         "fBodyAccskewnessY",
                         "fBodyAcckurtosisY",
                         "fBodyAccskewnessZ",
                         "fBodyAcckurtosisZ",
                         "fBodyAccbandsEnergy18-1",
                         "fBodyAccbandsEnergy916-1",
                         "fBodyAccbandsEnergy1724-1",
                         "fBodyAccbandsEnergy2532-1",
                         "fBodyAccbandsEnergy3340-1",
                         "fBodyAccbandsEnergy4148-1",
                         "fBodyAccbandsEnergy4956-1",
                         "fBodyAccbandsEnergy5764-1",
                         "fBodyAccbandsEnergy116-1",
                         "fBodyAccbandsEnergy1732-1",
                         "fBodyAccbandsEnergy3348-1",
                         "fBodyAccbandsEnergy4964-1",
                         "fBodyAccbandsEnergy124-1",
                         "fBodyAccbandsEnergy2548-1",
                         "fBodyAccbandsEnergy18-2",
                         "fBodyAccbandsEnergy916-2",
                         "fBodyAccbandsEnergy1724-2",
                         "fBodyAccbandsEnergy2532-2",
                         "fBodyAccbandsEnergy3340-2",
                         "fBodyAccbandsEnergy4148-2",
                         "fBodyAccbandsEnergy4956-2",
                         "fBodyAccbandsEnergy5764-2",
                         "fBodyAccbandsEnergy116-2",
                         "fBodyAccbandsEnergy1732-2",
                         "fBodyAccbandsEnergy3348-2",
                         "fBodyAccbandsEnergy4964-2",
                         "fBodyAccbandsEnergy124-2",
                         "fBodyAccbandsEnergy2548-2",
                         "fBodyAccbandsEnergy18-3",
                         "fBodyAccbandsEnergy916-3",
                         "fBodyAccbandsEnergy1724-3",
                         "fBodyAccbandsEnergy2532-3",
                         "fBodyAccbandsEnergy3340-3",
                         "fBodyAccbandsEnergy4148-3",
                         "fBodyAccbandsEnergy4956-3",
                         "fBodyAccbandsEnergy5764-3",
                         "fBodyAccbandsEnergy116-3",
                         "fBodyAccbandsEnergy1732-3",
                         "fBodyAccbandsEnergy3348-3",
                         "fBodyAccbandsEnergy4964-3",
                         "fBodyAccbandsEnergy124-3",
                         "fBodyAccbandsEnergy2548-3",
                         "fBodyAccJerkMeanX",
                         "fBodyAccJerkMeanY",
                         "fBodyAccJerkMeanZ",
                         "fBodyAccJerkStdX",
                         "fBodyAccJerkStdY",
                         "fBodyAccJerkStdZ",
                         "fBodyAccJerkmadX",
                         "fBodyAccJerkmadY",
                         "fBodyAccJerkmadZ",
                         "fBodyAccJerkmaxX",
                         "fBodyAccJerkmaxY",
                         "fBodyAccJerkmaxZ",
                         "fBodyAccJerkminX",
                         "fBodyAccJerkminY",
                         "fBodyAccJerkminZ",
                         "fBodyAccJerksma",
                         "fBodyAccJerkenergyX",
                         "fBodyAccJerkenergyY",
                         "fBodyAccJerkenergyZ",
                         "fBodyAccJerkiqrX",
                         "fBodyAccJerkiqrY",
                         "fBodyAccJerkiqrZ",
                         "fBodyAccJerkentropyX",
                         "fBodyAccJerkentropyY",
                         "fBodyAccJerkentropyZ",
                         "fBodyAccJerkmaxInds-X",
                         "fBodyAccJerkmaxInds-Y",
                         "fBodyAccJerkmaxInds-Z",
                         "fBodyAccJerkMeanFreqX",
                         "fBodyAccJerkMeanFreqY",
                         "fBodyAccJerkMeanFreqZ",
                         "fBodyAccJerkskewnessX",
                         "fBodyAccJerkkurtosisX",
                         "fBodyAccJerkskewnessY",
                         "fBodyAccJerkkurtosisY",
                         "fBodyAccJerkskewnessZ",
                         "fBodyAccJerkkurtosisZ",
                         "fBodyAccJerkbandsEnergy18-1",
                         "fBodyAccJerkbandsEnergy916-1",
                         "fBodyAccJerkbandsEnergy1724-1",
                         "fBodyAccJerkbandsEnergy2532-1",
                         "fBodyAccJerkbandsEnergy3340-1",
                         "fBodyAccJerkbandsEnergy4148-1",
                         "fBodyAccJerkbandsEnergy4956-1",
                         "fBodyAccJerkbandsEnergy5764-1",
                         "fBodyAccJerkbandsEnergy116-1",
                         "fBodyAccJerkbandsEnergy1732-1",
                         "fBodyAccJerkbandsEnergy3348-1",
                         "fBodyAccJerkbandsEnergy4964-1",
                         "fBodyAccJerkbandsEnergy124-1",
                         "fBodyAccJerkbandsEnergy2548-1",
                         "fBodyAccJerkbandsEnergy18-2",
                         "fBodyAccJerkbandsEnergy916-2",
                         "fBodyAccJerkbandsEnergy1724-2",
                         "fBodyAccJerkbandsEnergy2532-2",
                         "fBodyAccJerkbandsEnergy3340-2",
                         "fBodyAccJerkbandsEnergy4148-2",
                         "fBodyAccJerkbandsEnergy4956-2",
                         "fBodyAccJerkbandsEnergy5764-2",
                         "fBodyAccJerkbandsEnergy116-2",
                         "fBodyAccJerkbandsEnergy1732-2",
                         "fBodyAccJerkbandsEnergy3348-2",
                         "fBodyAccJerkbandsEnergy4964-2",
                         "fBodyAccJerkbandsEnergy124-2",
                         "fBodyAccJerkbandsEnergy2548-2",
                         "fBodyAccJerkbandsEnergy18-3",
                         "fBodyAccJerkbandsEnergy916-3",
                         "fBodyAccJerkbandsEnergy1724-3",
                         "fBodyAccJerkbandsEnergy2532-3",
                         "fBodyAccJerkbandsEnergy3340-3",
                         "fBodyAccJerkbandsEnergy4148-3",
                         "fBodyAccJerkbandsEnergy4956-3",
                         "fBodyAccJerkbandsEnergy5764-3",
                         "fBodyAccJerkbandsEnergy116-3",
                         "fBodyAccJerkbandsEnergy1732-3",
                         "fBodyAccJerkbandsEnergy3348-3",
                         "fBodyAccJerkbandsEnergy4964-3",
                         "fBodyAccJerkbandsEnergy124-3",
                         "fBodyAccJerkbandsEnergy2548-3",
                         "fBodyGyroMeanX",
                         "fBodyGyroMeanY",
                         "fBodyGyroMeanZ",
                         "fBodyGyroStdX",
                         "fBodyGyroStdY",
                         "fBodyGyroStdZ",
                         "fBodyGyromadX",
                         "fBodyGyromadY",
                         "fBodyGyromadZ",
                         "fBodyGyromaxX",
                         "fBodyGyromaxY",
                         "fBodyGyromaxZ",
                         "fBodyGyrominX",
                         "fBodyGyrominY",
                         "fBodyGyrominZ",
                         "fBodyGyrosma",
                         "fBodyGyroenergyX",
                         "fBodyGyroenergyY",
                         "fBodyGyroenergyZ",
                         "fBodyGyroiqrX",
                         "fBodyGyroiqrY",
                         "fBodyGyroiqrZ",
                         "fBodyGyroentropyX",
                         "fBodyGyroentropyY",
                         "fBodyGyroentropyZ",
                         "fBodyGyromaxInds-X",
                         "fBodyGyromaxInds-Y",
                         "fBodyGyromaxInds-Z",
                         "fBodyGyroMeanFreqX",
                         "fBodyGyroMeanFreqY",
                         "fBodyGyroMeanFreqZ",
                         "fBodyGyroskewnessX",
                         "fBodyGyrokurtosisX",
                         "fBodyGyroskewnessY",
                         "fBodyGyrokurtosisY",
                         "fBodyGyroskewnessZ",
                         "fBodyGyrokurtosisZ",
                         "fBodyGyrobandsEnergy18-1",
                         "fBodyGyrobandsEnergy916-1",
                         "fBodyGyrobandsEnergy1724-1",
                         "fBodyGyrobandsEnergy2532-1",
                         "fBodyGyrobandsEnergy3340-1",
                         "fBodyGyrobandsEnergy4148-1",
                         "fBodyGyrobandsEnergy4956-1",
                         "fBodyGyrobandsEnergy5764-1",
                         "fBodyGyrobandsEnergy116-1",
                         "fBodyGyrobandsEnergy1732-1",
                         "fBodyGyrobandsEnergy3348-1",
                         "fBodyGyrobandsEnergy4964-1",
                         "fBodyGyrobandsEnergy124-1",
                         "fBodyGyrobandsEnergy2548-1",
                         "fBodyGyrobandsEnergy18-2",
                         "fBodyGyrobandsEnergy916-2",
                         "fBodyGyrobandsEnergy1724-2",
                         "fBodyGyrobandsEnergy2532-2",
                         "fBodyGyrobandsEnergy3340-2",
                         "fBodyGyrobandsEnergy4148-2",
                         "fBodyGyrobandsEnergy4956-2",
                         "fBodyGyrobandsEnergy5764-2",
                         "fBodyGyrobandsEnergy116-2",
                         "fBodyGyrobandsEnergy1732-2",
                         "fBodyGyrobandsEnergy3348-2",
                         "fBodyGyrobandsEnergy4964-2",
                         "fBodyGyrobandsEnergy124-2",
                         "fBodyGyrobandsEnergy2548-2",
                         "fBodyGyrobandsEnergy18-3",
                         "fBodyGyrobandsEnergy916-3",
                         "fBodyGyrobandsEnergy1724-3",
                         "fBodyGyrobandsEnergy2532-3",
                         "fBodyGyrobandsEnergy3340-3",
                         "fBodyGyrobandsEnergy4148-3",
                         "fBodyGyrobandsEnergy4956-3",
                         "fBodyGyrobandsEnergy5764-3",
                         "fBodyGyrobandsEnergy116-3",
                         "fBodyGyrobandsEnergy1732-3",
                         "fBodyGyrobandsEnergy3348-3",
                         "fBodyGyrobandsEnergy4964-3",
                         "fBodyGyrobandsEnergy124-3",
                         "fBodyGyrobandsEnergy2548-3",
                         "fBodyAccMagMean",
                         "fBodyAccMagStd",
                         "fBodyAccMagmad",
                         "fBodyAccMagmax",
                         "fBodyAccMagmin",
                         "fBodyAccMagsma",
                         "fBodyAccMagenergy",
                         "fBodyAccMagiqr",
                         "fBodyAccMagentropy",
                         "fBodyAccMagmaxInds",
                         "fBodyAccMagMeanFreq",
                         "fBodyAccMagskewness",
                         "fBodyAccMagkurtosis",
                         "fBodyBodyAccJerkMagMean",
                         "fBodyBodyAccJerkMagStd",
                         "fBodyBodyAccJerkMagmad",
                         "fBodyBodyAccJerkMagmax",
                         "fBodyBodyAccJerkMagmin",
                         "fBodyBodyAccJerkMagsma",
                         "fBodyBodyAccJerkMagenergy",
                         "fBodyBodyAccJerkMagiqr",
                         "fBodyBodyAccJerkMagentropy",
                         "fBodyBodyAccJerkMagmaxInds",
                         "fBodyBodyAccJerkMagMeanFreq",
                         "fBodyBodyAccJerkMagskewness",
                         "fBodyBodyAccJerkMagkurtosis",
                         "fBodyBodyGyroMagMean",
                         "fBodyBodyGyroMagStd",
                         "fBodyBodyGyroMagmad",
                         "fBodyBodyGyroMagmax",
                         "fBodyBodyGyroMagmin",
                         "fBodyBodyGyroMagsma",
                         "fBodyBodyGyroMagenergy",
                         "fBodyBodyGyroMagiqr",
                         "fBodyBodyGyroMagentropy",
                         "fBodyBodyGyroMagmaxInds",
                         "fBodyBodyGyroMagMeanFreq",
                         "fBodyBodyGyroMagskewness",
                         "fBodyBodyGyroMagkurtosis",
                         "fBodyBodyGyroJerkMagMean",
                         "fBodyBodyGyroJerkMagStd",
                         "fBodyBodyGyroJerkMagmad",
                         "fBodyBodyGyroJerkMagmax",
                         "fBodyBodyGyroJerkMagmin",
                         "fBodyBodyGyroJerkMagsma",
                         "fBodyBodyGyroJerkMagenergy",
                         "fBodyBodyGyroJerkMagiqr",
                         "fBodyBodyGyroJerkMagentropy",
                         "fBodyBodyGyroJerkMagmaxInds",
                         "fBodyBodyGyroJerkMagMeanFreq",
                         "fBodyBodyGyroJerkMagskewness",
                         "fBodyBodyGyroJerkMagkurtosis",
                         "angletBodyAccMeangravity",
                         "angletBodyAccJerkMeangravityMean",
                         "angletBodyGyroMeangravityMean",
                         "angletBodyGyroJerkMeangravityMean",
                         "angleXgravityMean",
                         "angleYgravityMean",
                         "angleZgravityMean",
                         "activity",
                         "subject")


tidyData <- select(mergeData, tBodyAccMeanx,
                   tBodyAccmeanY,
                   tBodyAccMeanZ,
                   tBodyAccStdX,
                   tBodyAccStdY,
                   tBodyAccStdZ,
                   tGravityAccMeanX,
                   tGravityAccMeanY,
                   tGravityAccMeanZ,
                   tGravityAccStdX,
                   tGravityAccStdY,
                   tGravityAccStdZ,
                   tBodyAccJerkMeanX,
                   tBodyAccJerkMeanY,
                   tBodyAccJerkMeanZ,
                   tBodyAccJerkStdX,
                   tBodyAccJerkStdY,
                   tBodyAccJerkStdZ,
                   tBodyGyroMeanX,
                   tBodyGyroMeanY,	 
                   tBodyGyroMeanZ,
                   tBodyGyroStdX,
                   tBodyGyroStdY,
                   tBodyGyroStdZ,
                   tBodyGyroJerkMeanX,
                   tBodyGyroJerkMeanY,
                   tBodyGyroJerkMeanZ,
                   tBodyGyroJerkStdX,
                   tBodyGyroJerkStdY,
                   tBodyGyroJerkStdZ,
                   tBodyAccMagMean,
                   tBodyAccMagStd,
                   tGravityAccMagMean,
                   tGravityAccMagStd,
                   tBodyAccJerkMagMean,
                   tBodyAccJerkMagStd,
                   tBodyGyroMagMean,
                   tBodyGyroMagStd,
                   tBodyGyroJerkMagMean,
                   tBodyGyroJerkMagStd,
                   fBodyAccMeanX,
                   fBodyAccMeanY,
                   fBodyAccMeanZ,
                   fBodyAccStdX,
                   fBodyAccStdY,
                   fBodyAccStdZ,
                   fBodyAccMeanFreqX,
                   fBodyAccMeanFreqY,
                   fBodyAccMeanFreqZ,
                   fBodyAccJerkMeanX,
                   fBodyAccJerkMeanY,
                   fBodyAccJerkMeanZ,
                   fBodyAccJerkStdX,
                   fBodyAccJerkStdY,
                   fBodyAccJerkStdZ,
                   fBodyAccJerkMeanFreqX,
                   fBodyAccJerkMeanFreqY,
                   fBodyAccJerkMeanFreqZ,
                   fBodyGyroMeanX,
                   fBodyGyroMeanY,
                   fBodyGyroMeanZ,
                   fBodyGyroStdX,
                   fBodyGyroStdY,
                   fBodyGyroStdZ,
                   fBodyGyroMeanFreqX,
                   fBodyGyroMeanFreqY,
                   fBodyGyroMeanFreqZ,
                   fBodyAccMagMean,
                   fBodyAccMagStd,
                   fBodyBodyGyroMagMean,
                   fBodyBodyGyroMagStd,
                   fBodyBodyGyroMagMeanFreq,
                   fBodyBodyGyroJerkMagMean,
                   fBodyBodyGyroJerkMagStd,
                   fBodyBodyGyroJerkMagMeanFreq,
                   angletBodyAccMeangravity,
                   angletBodyAccJerkMeangravityMean,
                   angletBodyGyroMeangravityMean,
                   angletBodyGyroJerkMeangravityMean,
                   angleXgravityMean,
                   angleYgravityMean,
                   angleZgravityMean,
                   activity,
                   subject)

tidyData2 <- tidyData %>% group_by(activity, subject)%>%
  summarize(tBodyAccMeanx = mean(tBodyAccMeanx),
            tBodyAccMeanY = mean(tBodyAccmeanY),
            tBodyAccMeanZ = mean(tBodyAccMeanZ),
            tBodyAccStdX = mean(tBodyAccStdX),
            tBodyAccStdY = mean(tBodyAccStdY),
            tBodyAccStdZ = mean(tBodyAccStdZ),
            tGravityAccMeanX = mean(tGravityAccMeanX),
            tGravityAccMeanY = mean(tGravityAccMeanY),
            tGravityAccMeanZ = mean(tGravityAccMeanZ),
            tGravityAccStdX = mean(tGravityAccStdX),
            tGravityAccStdY = mean(tGravityAccStdY),
            tGravityAccStdZ = mean(tGravityAccStdZ),
            tBodyAccJerkMeanX = mean(tBodyAccJerkMeanX),
            tBodyAccJerkMeanY = mean(tBodyAccJerkMeanY),
            tBodyAccJerkMeanZ = mean(tBodyAccJerkMeanZ),
            tBodyAccJerkStdX = mean(tBodyAccJerkStdX),
            tBodyAccJerkStdY = mean(tBodyAccJerkStdY),
            tBodyAccJerkStdZ = mean(tBodyAccJerkStdZ),
            tBodyGyroMeanX = mean(tBodyGyroMeanX),
            tBodyGyroMeanY = mean(tBodyGyroMeanY),	 
            tBodyGyroMeanZ = mean(tBodyGyroMeanZ),
            tBodyGyroStdX = mean(tBodyGyroStdX),
            tBodyGyroStdY = mean(tBodyGyroStdY),
            tBodyGyroStdZ = mean(tBodyGyroStdZ),
            tBodyGyroJerkMeanX = mean(tBodyGyroJerkMeanX),
            tBodyGyroJerkMeanY = mean(tBodyGyroJerkMeanY),
            tBodyGyroJerkMeanZ = mean(tBodyGyroJerkMeanZ),
            tBodyGyroJerkStdX = mean(tBodyGyroJerkStdX),
            tBodyGyroJerkStdY = mean(tBodyGyroJerkStdY),
            tBodyGyroJerkStdZ = mean(tBodyGyroJerkStdZ),
            tBodyAccMagMean = mean(tBodyAccMagMean),
            tBodyAccMagStd = mean(tBodyAccMagStd),
            tGravityAccMagMean = mean(tGravityAccMagMean),
            tGravityAccMagStd = mean(tGravityAccMagStd),
            tBodyAccJerkMagMean = mean(tBodyAccJerkMagMean),
            tBodyAccJerkMagStd = mean(tBodyAccJerkMagStd),
            tBodyGyroMagMean = mean(tBodyGyroMagMean),
            tBodyGyroMagStd = mean(tBodyGyroMagStd),
            tBodyGyroJerkMagMean = mean(tBodyGyroJerkMagMean),
            tBodyGyroJerkMagStd = mean(tBodyGyroJerkMagStd),
            fBodyAccMeanX = mean(fBodyAccMeanX),
            fBodyAccMeanY = mean(fBodyAccMeanY),
            fBodyAccMeanZ = mean(fBodyAccMeanZ),
            fBodyAccStdX = mean(fBodyAccStdX),
            fBodyAccStdY = mean(fBodyAccStdY),
            fBodyAccStdZ = mean(fBodyAccStdZ),
            fBodyAccMeanFreqX = mean(fBodyAccMeanFreqX),
            fBodyAccMeanFreqY = mean(fBodyAccMeanFreqY),
            fBodyAccMeanFreqZ = mean(fBodyAccMeanFreqZ),
            fBodyAccJerkMeanX = mean(fBodyAccJerkMeanX),
            fBodyAccJerkMeanY = mean(fBodyAccJerkMeanY),
            fBodyAccJerkMeanZ = mean(fBodyAccJerkMeanZ),
            fBodyAccJerkStdX = mean(fBodyAccJerkStdX),
            fBodyAccJerkStdY = mean(fBodyAccJerkStdY),
            fBodyAccJerkStdZ = mean(fBodyAccJerkStdZ),
            fBodyAccJerkMeanFreqX = mean(fBodyAccJerkMeanFreqX),
            fBodyAccJerkMeanFreqY = mean(fBodyAccJerkMeanFreqY),
            fBodyAccJerkMeanFreqZ = mean(fBodyAccJerkMeanFreqZ),
            fBodyGyroMeanX = mean(fBodyGyroMeanX),
            fBodyGyroMeanY = mean(fBodyGyroMeanY),
            fBodyGyroMeanZ = mean(fBodyGyroMeanZ),
            fBodyGyroStdX = mean(fBodyGyroStdX),
            fBodyGyroStdY = mean(fBodyGyroStdY),
            fBodyGyroStdZ = mean(fBodyGyroStdZ),
            fBodyGyroMeanFreqX = mean(fBodyGyroMeanFreqX),
            fBodyGyroMeanFreqY = mean(fBodyGyroMeanFreqY),
            fBodyGyroMeanFreqZ = mean(fBodyGyroMeanFreqZ),
            fBodyAccMagMean = mean(fBodyAccMagMean),
            fBodyAccMagStd = mean(fBodyAccMagStd),
            fBodyBodyGyroMagMean = mean(fBodyBodyGyroMagMean),
            fBodyBodyGyroMagStd = mean(fBodyBodyGyroMagStd),
            fBodyBodyGyroMagMeanFreq = mean(fBodyBodyGyroMagMeanFreq),	
            fBodyBodyGyroJerkMagMean = mean(fBodyBodyGyroJerkMagMean),
            fBodyBodyGyroJerkMagStd = mean(fBodyBodyGyroJerkMagStd),
            fBodyBodyGyroJerkMagMeanFreq = mean(fBodyBodyGyroJerkMagMeanFreq),
            angletBodyAccMeangravity = mean(angletBodyAccMeangravity),
            angletBodyAccJerkMeangravityMean = mean(angletBodyAccJerkMeangravityMean),
            angletBodyGyroMeangravityMean = mean(angletBodyGyroMeangravityMean),
            angletBodyGyroJerkMeangravityMean = mean(angletBodyGyroJerkMeangravityMean),
            angleXgravityMean = mean(angleXgravityMean),
            angleYgravityMean = mean(angleYgravityMean),
            angleZgravityMean = mean(angleZgravityMean))              




activity <- vector("numeric", length = 1)
td <- data.frame(activity)
numrows <- nrow(tidyData2)
for (i in 1:numrows){
  if (tidyData2 [i,1]  == '1') {
    td[i, 1] <- "WALKING"
  }
  if (tidyData2 [i,1] == '2') {
    td[i, 1] <- "WALKING_UPSTAIRS"
  }
  if (tidyData2[i,1] == '3') {
    td[i, 1] <- "WALKING_DOWNSTAIRS"
  }
  if (tidyData2[i,1] == '4') {
    td[i, 1] <- "SITTING"
  }
  if (tidyData2[i,1] == '5') {
    td[i, 1] <- "STANDING"
  }
  if (tidyData2[i,1] == '6') {
    td[i, 1] <- "LAYING"
  }
}


numrows <- nrow(tidyData2)
rownum <- nrow(td)
colnum <- ncol(tidyData2)
for (i in 1:numrows) {
  for (i2 in 2:colnum) {
    if (colnum >= i2) {
      td[i,i2] <- cbind(tidyData2[i,i2])
    }
 }
} 

write.csv(td, file="tidyDataset2.csv")

